### ISSUE TITLE
FEAT: Make a 3d second Game

### ISSUE THREAD

**Issue by Thomaltarix** [FppEpitech/R-Type#267]
**Is your feature request related to a problem? Please describe.**
Since we implemented a complete game engine, we'll need to create another complete game that is a 3d one.

**Describe the solution you'd like**
To create the game, we'll need to:
- [x] Create the second game architecture #269 
- [x] Find assets (player, tree, rock, pickaxe) #268
- [x] Implement systems to spawn a player #276 
- [x] Implement systems to move the player #284 
- [ ] Implement systems to update player position thanks to the server
- [x] Implement the Camera in third person on the player #296 
- [x] Implement the ground #296 
- [x] Implement the spawn of trees #309 
- [x] Implement collision with the players and the ground and the hail bay #296
