### ISSUE TITLE
FEAT: Create the client scene manager

### ISSUE THREAD

**Issue by Thomaltarix** [FppEpitech/R-Type#41]
**Is your feature request related to a problem? Please describe.**
Some feature of the client are not linked to the server, like the menus and the settings.
For that, we need a system that handle the switch of the scenes, the set up of them and handle the menu interaction

**Describe the solution you'd like**
I'll create a scene manager for the client.
This scene manager should :
- [x] Open the scene files and load their content, then save it into the registers or maps. #43  
- [x] Be able to manage the scene change. #44 
- [x] Receive game input from the graphical part and handle it. #36 

**Additional context**
Configuration files will be formatted in `.json`. I'll use the [jsoncpp](https://en.wikibooks.org/wiki/JsonCpp) library to parse those files.
